AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  plugins:
    - rubocop-performance
    - rubocop-rake
    - rubocop-rspec

Layout/ClassStructure:
  Enabled: true

Metrics/BlockLength:
  AllowedMethods:
    - describe
    - context

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/EndlessMethod:
  EnforcedStyle: require_single_line

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
