AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - "setup-ruby/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
