AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  plugins:
    - rubocop-performance
    - rubocop-rake
    - rubocop-rspec
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
