$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
words:
  - bindir
  - diffable
  - Katachi
  - kwargs
  - pipefail
  - popen
  - prevalidate
  - procs
  - readlines
  - rubocop
  - rubygems
  - shapeables
  - Tannas
