$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
words:
  - bindir
  - Katachi
  - kwargs # keyword args
  - pipefail
  - popen
  - readlines
  - rubocop
  - rubygems
  - Tannas
