$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
words:
  - autorun
  - bindir
  - diffable
  - jtannas
  - kata
  - Katachi
  - kwargs
  - PEBKAC
  - pipefail
  - popen
  - precompare
  - procs
  - Rakefile
  - readlines
  - rubocop
  - rubygems
  - shapeables
  - Tannas
  - testtask
