name: Pull Request Tests

on:
  pull_request:

jobs:
  cspell:
    runs-on: ubuntu-latest
    name: Spellchecking
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v6
        with:
          incremental_files_only: false
  rubocop:
    runs-on: ubuntu-latest
    name: Rubocop
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: jtannas/setup-ruby
          ref: issue-716-multiple-tool-versions
          path: setup-ruby
      - uses: ./setup-ruby
        with:
          bundler-cache: true
      - run: bundle exec rubocop
