name: Pull Request Tests

on:
  pull_request:

jobs:
  cspell:
    runs-on: ubuntu-latest
    name: Spellchecking
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v6
        with:
          incremental_files_only: false
  rubocop:
    runs-on: ubuntu-latest
    name: Rubocop
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rubocop
  rspec:
    runs-on: ubuntu-latest
    name: RSpec [Ruby=${{ matrix.ruby }}]
    continue-on-error: true # Continue testing other Ruby versions even if one fails
    permissions:
      contents: read
    strategy:
      matrix:
        ruby:
          - "3.2.4"
          - "3.3.3"
          - "3.4.2"
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rspec
      - name: Upload Coverage
        uses: coverallsapp/github-action@v2
        with:
          flag-name: rspec; Ruby ${{ matrix.ruby }}
